joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint1
  pid:
    {
      p: 20,
      i: 0.0,
      d: 0.8,
      i_clamp_max: 1,
      i_clamp_min: -1,
      antiwindup: true,
    }
joint1_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: joint1
  pid: { p: 0.9, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true }